<?php

/**
 * @file media_youku/media_youku.module
 *
 * Media: Youku provides a stream wrapper and formatters for videos provided
 * by Youku, available at http://youku.com/.
 *
 */

// A registry of variable_get defaults.
include_once ('includes/media_youku.variables.inc');

// Hooks and callbacks for integrating with Styles module for display.
// @todo Can save a little overhead for people without Styles module by wrapping
//   this inside a module_exists('styles'). However, is that safe to do in
//   global context? If not, is there any down side to doing it in hook_init()?
include_once ('includes/media_youku.styles.inc');

// Hooks and callbacks for integrating with File Entity module for display.
include_once ('includes/media_youku.formatters.inc');

/**
 * Implements hook_media_internet_providers().
 */
function media_youku_media_internet_providers() {
  $path = drupal_get_path('module', 'media_youku');
  return array(
    'MediaInternetYoukuHandler' => array(
      'title' => 'youku',
      'image' => $path . '/images/stream-youku.png',
    ),
  );
}

/**
 * Implements hook_stream_wrappers().
 */
function media_youku_stream_wrappers() {
  return array(
    'youku' => array(
      'name' => t('Youku videos'),
      'class' => 'MediaYoukuStreamWrapper',
      'description' => t('Videos provided by Youku.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function media_youku_theme($existing, $type, $theme, $path) {
  return array(
    'media_youku_preview_style' => array(
      'variables' => array('style_name' => NULL),
      'file' => 'media_youku.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_youku_field_formatter_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
      'file' => 'media_youku.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_youku_video' => array(
      'variables' => array('uri' => NULL, 'width' => NULL, 'height' => NULL, 'autoplay' => NULL, 'fullscreen' => NULL),
      'file' => 'media_youku.theme.inc',
      'path' => $path . '/includes/themes',
      'template' => 'media-youku-video',
    ),
    'media_youku_embed' => array(
      'variables' => array('style_name' => NULL, 'uri' => NULL, 'alt' => NULL, 'title' => NULL),
      'file' => 'media_youku.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_youku_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
      'file' => 'media_youku.theme.inc',
      'path' => $path . '/includes/themes',
    ),
  );
}

/**
 * Implements hook_media_parse().
 *
 * @todo This hook should be deprecated. Refactor Media module to not call it
 *   any more, since media_internet should be able to automatically route to the
 *   appropriate handler.
 */
function media_youku_media_parse($embed_code) {
  $handler = new MediaInternetYoukuHandler($embed_code);
  return $handler->parse($embed_code);
}

/**
 * Implements hook_media_format_form_prepare_alter().
 */
function media_youku_media_format_form_prepare_alter(&$form, &$form_state, $media) {
  $settings = array('autosubmit' => ($media->type == "video"));
  drupal_add_js(array('media_format_form' => $settings), 'setting');
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_youku_ctools_plugin_api($owner, $api) {
  static $api_versions = array(
    'file_entity' => array(
      'file_default_displays' => 1,
    ),
  );
  if (isset($api_versions[$owner][$api])) {
    return array('version' => $api_versions[$owner][$api]);
  }
}

